#coding=utf-8
"""
Django settings for MyBlog project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPOSITORY_ROOT = os.path.dirname(BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5ecsh3grgmv5j(gz0o-x=@==*ccf1-y#rmtos!3z)1t4fkpi&@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'blog',
    'litdev_auth',
    'litdev_comments',
    'ToolsHelper', #工具APP
    'pagination',  #分页工具
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
     'pagination.middleware.PaginationMiddleware',
)

ROOT_URLCONF = 'MyBlog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "ToolsHelper/templates/"),], #
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyBlog.wsgi.application'

#文件保存方式，0为保存到本地，1为保存到七牛云,要与下面“自定义上传属性”配合一起使用###################
FILE_SAVE_DISK_TYPE = 1

#自定义上传属性
#DEFAULT_FILE_STORAGE = 'ToolsHelper.OverImageStorage.ImageStorage'
DEFAULT_FILE_STORAGE = 'qiniustorage.backends.QiniuStaticStorage'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# 'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'MyBlog',
        'USER': '',  #登陆用户名
        'PASSWORD': '', #登陆密码
        'HOST': '', #数据库地址
        'PORT': '3306', #数据库端口
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# 这个是默认设置，默认会找 STATICFILES_DIRS 中所有文件夹和各app下的 static 文件夹
STATICFILES_FINDERS=(
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder"
)

#日志配置#############################
LOG_FILE = "./all.log"
LOGGING={
    'version':1,
    'disable_existing_loggers': True,
    'filters':{
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
            }
    },
    'formatters': {
        'simple': {
           'format': '[%(levelname)s] %(module)s : %(message)s'
            },
        'verbose': {
            'format': '[%(asctime)s] [%(levelname)s] %(module)s : %(message)s'
        }
     },
     'handlers': {
        'null': {
            'level': 'DEBUG',
            'class': 'django.utils.log.NullHandler',
            },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
            },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'formatter': 'verbose',
            'filename': LOG_FILE,
            'mode': 'a',
            },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false']
            }
        },
    'loggers': {
        '': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
            },
        'django': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
            },
        'django.request': {
            'handlers': ['mail_admins', 'console'],
            'level': 'ERROR',
            'propagate': True,
           },
        }
}

#缓存配置###########################
CACHES={
    'default':{
        'BACKEND':'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION':'unique-snowflake',
        'options':{
            'MAX_ENTRIES':1024,
        }
    },
    'memcache':{
        'BACKEND':'django.core.cache.backends.memcached.MemcachedCache',
        #'LOCATION':'unix:/home/billvsme/memcached.sock',
        'LOCATION':'127.0.0.1:11211',
        'options':{
            'MAX_ENTRIES':1024,
        }
    }
}

#分页配置#####################
PAGE_NUM = 5

#email 配置############################

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = ''  #SMTP地址，例如:smtp.qq.com
EMAIL_PORT = 25  #SMTP端口
EMAIL_HOST_USER = ''  #邮箱地址
EMAIL_HOST_PASSWORD = '' #邮箱密码
EMAIL_SUBJECT_PREFIX = u'xxxx' #为邮件Subject-line前缀,默认是'[django]'
EMAIL_USE_TLS = True  #与SMTP服务器通信时，是否启动TLS链接(安全链接)。默认是false

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

#七牛配置###############
QINIU_ACCESS_KEY = ''
QINIU_SECRET_KEY = ''
QINIU_BUCKET_NAME = ''
QINIU_BUCKET_DOMAIN = ''


#访问本地上传的文件需要，没有这句就无法访问上传的文件，结合URL后面的+一句使用
MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads/')

#是否启用评论
COMMENTS_ENABLE = True
